// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: BasementControls

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x818181), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonAllOn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonAllOn, lv_pct(10));
    lv_obj_set_height(ui_ButtonAllOn, lv_pct(10));
    lv_obj_set_x(ui_ButtonAllOn, lv_pct(67));
    lv_obj_set_y(ui_ButtonAllOn, lv_pct(85));
    lv_obj_add_flag(ui_ButtonAllOn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonAllOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonAllOn, lv_color_hex(0x27324A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAllOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonAllOn, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonAllOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonAllOn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonAllOn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ButtonAllOn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ButtonAllOn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonAllOnLabel = lv_label_create(ui_ButtonAllOn);
    lv_obj_set_width(ui_ButtonAllOnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonAllOnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonAllOnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonAllOnLabel, "Alle An");

    ui_ButtonAllOff = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonAllOff, lv_pct(10));
    lv_obj_set_height(ui_ButtonAllOff, lv_pct(10));
    lv_obj_set_x(ui_ButtonAllOff, lv_pct(80));
    lv_obj_set_y(ui_ButtonAllOff, lv_pct(85));
    lv_obj_add_flag(ui_ButtonAllOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonAllOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonAllOff, lv_color_hex(0x27324A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAllOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonAllOff, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonAllOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonAllOff, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonAllOff, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ButtonAllOff, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ButtonAllOff, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonAllOffLabel = lv_label_create(ui_ButtonAllOff);
    lv_obj_set_width(ui_ButtonAllOffLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonAllOffLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonAllOffLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonAllOffLabel, "Alle Aus");

    ui_PanelTop = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelTop, lv_pct(100));
    lv_obj_set_height(ui_PanelTop, lv_pct(15));
    lv_obj_clear_flag(ui_PanelTop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTop, lv_color_hex(0x27324A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHeader = lv_label_create(ui_PanelTop);
    lv_obj_set_width(ui_LabelHeader, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_LabelHeader, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_LabelHeader, lv_pct(0));
    lv_obj_set_y(ui_LabelHeader, lv_pct(-15));
    lv_label_set_text(ui_LabelHeader, "Keller Lichtsteuerung");
    lv_obj_set_style_text_color(ui_LabelHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHeader, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, lv_pct(6));
    lv_obj_set_height(ui_Switch1, lv_pct(5));
    lv_obj_set_x(ui_Switch1, 500);
    lv_obj_set_y(ui_Switch1, 300);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x696969), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x27324A), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_Switch1, lv_color_hex(0xE5BC09), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch1, 40, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch1, 20, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_SwitchLabel1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SwitchLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchLabel1, 500);
    lv_obj_set_y(ui_SwitchLabel1, 330);
    lv_label_set_text(ui_SwitchLabel1, "Hauptkeller");
    lv_obj_set_style_text_font(ui_SwitchLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch2, lv_pct(6));
    lv_obj_set_height(ui_Switch2, lv_pct(5));
    lv_obj_set_x(ui_Switch2, 570);
    lv_obj_set_y(ui_Switch2, 150);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x696969), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x27324A), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_Switch2, lv_color_hex(0xE5BC09), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch2, 40, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch2, 20, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_SwitchLabel2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SwitchLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchLabel2, 570);
    lv_obj_set_y(ui_SwitchLabel2, 180);
    lv_label_set_text(ui_SwitchLabel2, "Waschkeller");
    lv_obj_set_style_text_font(ui_SwitchLabel2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch3, lv_pct(6));
    lv_obj_set_height(ui_Switch3, lv_pct(5));
    lv_obj_set_x(ui_Switch3, 310);
    lv_obj_set_y(ui_Switch3, 150);

    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x696969), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x27324A), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_Switch3, lv_color_hex(0xE5BC09), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch3, 40, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch3, 20, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_SwitchLabel3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SwitchLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchLabel3, 310);
    lv_obj_set_y(ui_SwitchLabel3, 180);
    lv_label_set_text(ui_SwitchLabel3, "Nordkeller");
    lv_obj_set_style_text_font(ui_SwitchLabel3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch4, lv_pct(6));
    lv_obj_set_height(ui_Switch4, lv_pct(5));
    lv_obj_set_x(ui_Switch4, 150);
    lv_obj_set_y(ui_Switch4, 300);

    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x696969), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x27324A), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_Switch4, lv_color_hex(0xE5BC09), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_Switch4, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_Switch4, 40, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_Switch4, 20, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_SwitchLabel4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SwitchLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchLabel4, 150);
    lv_obj_set_y(ui_SwitchLabel4, 330);
    lv_label_set_text(ui_SwitchLabel4, "Heizungs- und\nEinmachkeller");
    lv_obj_set_style_text_font(ui_SwitchLabel4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonAllOn, ui_event_ButtonAllOn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonAllOff, ui_event_ButtonAllOff, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);

}
